### ISSUE TITLE
Scroll preview window with `<c-d>` and `<c-u>` 

### ISSUE THREAD

**Issue by axieax** [Zane-/howdoi.nvim#1]
Hi, love the idea of this plugin! It seems that one is unable to scroll the preview window to see the full results with the actions of `<c-d>` and `<c-u>`, resulting in the following error:

![image](https://user-images.githubusercontent.com/62098008/172217843-beb27edb-2b16-4fe1-8711-89d5c691056d.png)

**Comment by Zane-** [comment]
Hmm I've been trying to figure out a way to do this. `howdoi` doesn't support paging, I've opened [#463](https://github.com/gleitz/howdoi/issues/463) to them to add an option. 

The easiest way would just be to pipe the output into `bat` or `less`, but telescope doesn't support piping in their built-in terminal command previewer, so out of luck there.

**Comment by Zane-** [comment]
Figured it out, scrolling with <c-d> and <c-u> should work now as intended (only if you have bash installed though).

**Comment by Zane-** [comment]
Kk should be good to go now, note that you have to specify a command_executor in the options if you don't have `bash` installed. This has to be something that can take a command to run like `bash -c`.

**Comment by axieax** [comment]
This is amazing!! :))
