### ISSUE TITLE
Allow passing a theme options to the picker to customize its appearance

### ISSUE THREAD

**Issue by akinsho** [Zane-/howdoi.nvim#3]
Hi @Zane-,

Thanks for your work on this plugin, I hadn't heard of `howdoi` before and have been looking for something like it. One thing I'm trying to do though is to change the appearance of the picker. by default, it uses my default layout, but I'd like to change it for the plugin. Most telescope extensions tend to take the options passed to the picker itself, e.g.

```lua
require('telescope').extension.howdoi.howdoi(require('telescope.themes').get_dropdown())
```
however currently, options are not passed in this way and a user cannot change the appearance of the pickers for this plugin.

**Comment by Zane-** [comment]
Hmm I'm not quite sure how to expose the setup function like that, do you have an example I can look at?

This is possible if you just pass the options to the `extensions` section in telescope's setup function, like so:

```
require('telescope').setup({
  extensions = {
    howdoi = require('telescope.themes').get_dropdown(),
  },
})
```

The options just needs to be a table, so if you also wanted to change the default `num_answers` option, you would need to extend the table returned by the theme

**Comment by akinsho** [comment]
@Zane- that's great that's more or less what I wanted also seems like a cleaner way to do it, I think so other extensions essentially pass the argument in the function they export to the picker which is how you end up with the example I showed above but I personally prefer this mechanism anyway

**Comment by Zane-** [comment]
Awesome, added a section to the README on applying a theme and also setting the extension options
